import { OnInit, EventEmitter } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { Button, ObjectTree, ButtonGroup, HoverButton } from '../../model';
import { ButtonGroupList, HoverButtonList } from '../../model/button-group.model';
import { FormDiaplyMode } from '../../../form/model';
import { Ability } from '@casl/ability';
export declare class ButtonGroupComponent implements OnInit {
    private ability;
    form: FormGroup;
    formDisplayMode: FormDiaplyMode;
    sourceIdentifier: string;
    sourceIndex: number;
    widgetArrayIndex: number;
    _buttons: Array<Button | ButtonGroup | HoverButton>;
    get buttons(): Array<Button | ButtonGroup | HoverButton>;
    set buttons(_buttons: Array<Button | ButtonGroup | HoverButton>);
    context: any;
    originalData: any;
    buttonRoute: Array<string>;
    parentHierarchy: ObjectTree;
    disabled: boolean;
    onClick: EventEmitter<any>;
    onIconClick: EventEmitter<any>;
    buttonLists: Array<Array<Button> | ButtonGroupList | HoverButtonList>;
    buttonListsType: Array<string>;
    displayDesktopDD: boolean;
    displayTabletDD: boolean;
    displayMobileDD: boolean;
    hoverButtonLists: Array<Array<Button> | ButtonGroupList | HoverButtonList>;
    constructor(ability: Ability);
    ngOnInit(): void;
    hasMobileButton(displayIn: string): boolean;
    changeButtonTypeToGhost(): void;
    getButtonList(): void;
    isGroupAdded(groupIdentifier: string, buttonLists: Array<Array<Button> | ButtonGroupList | HoverButtonList>): boolean;
    getGroupButton(groupIdentifier: string, buttonLists: Array<Array<Button> | ButtonGroupList | HoverButtonList>): boolean;
    getHoverButtons(): HoverButtonList;
    getButtonType(): void;
    isButtonGroup(buttonList: Array<Button> | ButtonGroupList | HoverButtonList): boolean;
    isChipGroup(buttonList: Array<Button> | ButtonGroupList | HoverButtonList): boolean;
    isButtonHover(buttonList: Array<Button> | ButtonGroupList | HoverButtonList): boolean;
    isButtonArray(buttonList: Array<Button> | ButtonGroupList | HoverButtonList): boolean;
    click(event: any): void;
    iconClick(event: any): void;
}
